### ISSUE TITLE
Spelling error in source

### ISSUE THREAD

**Issue by PvdBerg1998** [bloom42/misspell#1]
Congrats on your first Rust tool 😄 Just to be annoying, you should use the tool on itself 😉 
https://github.com/bloom42/misspell/blob/master/src/main.rs#L9 : `dictionnary` should be `dictionary`.
Also a grammar mistake at https://github.com/bloom42/misspell/blob/master/src/main.rs#L31 `an hashmap` should be `a hashmap`.

**Comment by z0mbie42** [comment]
Ooops, thank you !
I will add a lint step while setting up CI/CD to use itself it's source code.

**Comment by z0mbie42** [comment]
fixed in 341fa18d20340ae6f3efcdffab4f2a40081617e2

**Comment by z0mbie42** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [account](https://trello.com/c/jN4LlRa3/55-account)
