### ISSUE TITLE
Document design restrictions for contributors

### ISSUE THREAD

**Issue by epage** [bloom42/misspell#17]
Could you elaborate on this policy in a contributing guide?

I'd be interested to know where is the line for adding dependencies (see #16). For example, it sounds like you want to remove assert_fs despite it being a dev-dependency which means it only impacts contributors to this project.

Similarly, I have use cases for this program that would call it thousands of times where extra on the load times will add up (yes, other parts are slow, was doing one major change at a time).See #10.

**Comment by z0mbie42** [comment]
Hi.

I apologize for that being not clear as of today.

Bloom being a new project I hadn't time to publicly expose contribution guidelines. 

I'll put online in the next 2 days contribution guidelines here: https://opensource.bloom.sh/contributing with related security policies.

Dev dependencies are as much important as other kind of dependencies as a compromise of any of their peer dependencies may compromise contributors' systems which should be avoided at any price.

I've reopened #10 to find alternatives to `phf` to fit your use case.

**Comment by epage** [comment]
> On the other hand it introduce an external dependency which is not desirable for security reasons.

Rust puts value on shared crates rather than trying to push everything in the stdlib.  Restricting myself to "external crate only when absolutely required" is just too big of a constraint for me to consider it worthwhile to contribute.  I think I'll instead go work on my own crate to serve this role (not a fork so I can use the recommended licenses for crates, MIT+Apache).
