### ISSUE TITLE
Offer dynamic spelling corrections

### ISSUE THREAD

**Issue by epage** [bloom42/misspell#7]
Use something like [`ngrammatic`](https://crates.io/crates/ngrammatic) to offer suggested fixes.

**Comment by z0mbie42** [comment]
I'm not sure to understand what you mean. Fix is already proposed as the word associate a common misspell with it's fix instead of using algorithms like levenshtein.

**Comment by epage** [comment]
Currently, the only misspellings that can be detected are if the misspelling exists in the dictionary.
- This limits what misspellings can be detected
- This won't work for #6.  

So I guess the question is whether to expand in this direction or not.  I guess you could offer a conservative mode (current) and a fuzzy mode (this issue).
